import { NextResponse } from "next/server";

export async function GET() {
  const adapters = [
    {
      id: "apisetu",
      name: "APIsetu (GST Exact Turnover)",
      type: "government_tax",
      status: process.env.APISETU_API_KEY ? "live" : "sandbox",
      latencyMs: 142,
      circuitBreaker: "closed",
      endpoint: "https://apisetu.gov.in/gst/v1/turnover",
      reportsSupported: ["gst_exact_turnover", "gst_slab_check"],
    },
    {
      id: "gst_supreme",
      name: "GST Supreme Report (OTP Flow)",
      type: "tax_filing_history",
      status: process.env.GST_PORTAL_API_KEY ? "live" : "sandbox",
      latencyMs: 180,
      circuitBreaker: "closed",
      endpoint: "https://services.gst.gov.in/services/api/returns",
      reportsSupported: ["gst_supreme_report"],
    },
    {
      id: "cibil_commercial",
      name: "TransUnion CIBIL Commercial API",
      type: "credit_bureau",
      status: process.env.CIBIL_API_KEY ? "live" : "sandbox",
      latencyMs: 210,
      circuitBreaker: "closed",
      endpoint: "https://api.cibil.com/commercial/v1/report",
      reportsSupported: ["bureau_report"],
    },
    {
      id: "experian",
      name: "Experian Commercial Bureau (Fallback #1)",
      type: "credit_bureau",
      status: process.env.EXPERIAN_API_KEY ? "live" : "sandbox",
      latencyMs: 195,
      circuitBreaker: "standby",
      endpoint: "https://api.experian.in/commercial/v2",
      reportsSupported: ["bureau_report"],
    },
    {
      id: "crif_high_mark",
      name: "CRIF High Mark API (Fallback #2)",
      type: "credit_bureau",
      status: process.env.CRIF_API_KEY ? "live" : "sandbox",
      latencyMs: 205,
      circuitBreaker: "standby",
      endpoint: "https://api.crifhighmark.com/v1",
      reportsSupported: ["bureau_report"],
    },
    {
      id: "kyc_aggregator",
      name: "Karza / Digitap / Perfios KYC Aggregator",
      type: "identity_corporate",
      status: "sandbox",
      latencyMs: 110,
      circuitBreaker: "closed",
      endpoint: "https://api.karza.in/v3",
      reportsSupported: [
        "mobile_to_pan",
        "mobile_identity",
        "mobile_to_address",
        "company_supreme_report",
        "msme_report",
        "director_details",
        "find_someone",
      ],
    },
    {
      id: "ecourts",
      name: "e-Courts Case Aggregator",
      type: "judicial_records",
      status: "sandbox",
      latencyMs: 160,
      circuitBreaker: "closed",
      endpoint: "https://services.ecourts.gov.in/ecourtindia_v6",
      reportsSupported: ["court_case_history"],
    },
    {
      id: "cctns_fir",
      name: "CCTNS Police FIR Database",
      type: "law_enforcement",
      status: "sandbox",
      latencyMs: 140,
      circuitBreaker: "closed",
      endpoint: "https://digitalpolice.gov.in/cctns/v1",
      reportsSupported: ["fir_check"],
    },
    {
      id: "dgft_icegate",
      name: "DGFT / ICEGATE Import Export Gateway",
      type: "trade_customs",
      status: "sandbox",
      latencyMs: 130,
      circuitBreaker: "closed",
      endpoint: "https://dgft.gov.in/api/v1/iec",
      reportsSupported: ["import_export_report"],
    },
    {
      id: "delivery_graph",
      name: "E-Commerce Delivery Graph (Swiggy, Zomato, Amazon, Meesho)",
      type: "address_enrichment",
      status: "sandbox",
      latencyMs: 120,
      circuitBreaker: "closed",
      endpoint: "https://delivery-graph.chaanbean.in/v1",
      reportsSupported: ["address_enrichment"],
    },
    {
      id: "it_gst_ref",
      name: "Income Tax & GST Portal Reference Lookup",
      type: "legal_notice_acknowledgment",
      status: process.env.IT_PORTAL_API_KEY ? "live" : "sandbox",
      latencyMs: 95,
      circuitBreaker: "closed",
      endpoint: "https://eportal.incometax.gov.in/iec/foservices/api/ref",
      reportsSupported: ["legal_notice_gov_ref"],
    },
  ];

  const liveCount = adapters.filter((a) => a.status === "live").length;
  const sandboxCount = adapters.filter((a) => a.status === "sandbox").length;

  return NextResponse.json({
    timestamp: new Date().toISOString(),
    summary: {
      totalAdapters: adapters.length,
      liveCount,
      sandboxCount,
      failingCount: 0,
    },
    adapters,
  });
}
