import type { LoanProduct } from "./types";

export const CAPITALX_LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: "home-loan",
    name: "Home Loan",
    shortName: "Home Loan",
    category: "Property & Housing",
    facilityType: "term_loan",
    badge: "Lowest Interest Rate",
    rateText: "From 8.35% p.a.",
    annualRate: 8.35,
    minAmount: 500000,
    maxAmount: 100000000,
    defaultAmount: 4500000,
    minTenureYears: 1,
    maxTenureYears: 30,
    defaultTenureYears: 20,
    description: "Finance the purchase of a new flat, resale property, bungalow construction, or land purchase at institutional interest rates.",
    highlights: [
      "Up to 30 years repayment tenure",
      "Zero prepayment penalty on floating rates",
      "Tax deductions under Section 80C & 24(b)",
      "Express title deed legal & technical clearance",
    ],
    eligibilityCriteria: [
      "Salaried: Min net monthly income ₹25,000",
      "Self-Employed: Min 2 years profitable business track record",
      "CIBIL score 700+ preferred",
      "Property with clear sanctioned plan & marketable title",
    ],
    requiredDocuments: [
      "PAN Card & Aadhaar Card",
      "Last 6 months bank statements",
      "Last 2 years ITR with computation of income",
      "Agreement for Sale / Allotment letter / Property title chain",
    ],
    matchedLenders: [
      {
        id: "sbi",
        name: "State Bank of India",
        type: "Public Sector Bank",
        logoText: "SBI",
        indicativeRate: "8.35% – 8.65%",
        maxDisbursalDays: 5,
        matchScore: 96,
        featureHighlight: "Lowest processing fee & concessional women borrower rate",
      },
      {
        id: "hdfc",
        name: "HDFC Bank",
        type: "Private Commercial Bank",
        logoText: "HDFC",
        indicativeRate: "8.40% – 8.85%",
        maxDisbursalDays: 3,
        matchScore: 94,
        featureHighlight: "Same-day in-principle digital sanction",
      },
      {
        id: "icici",
        name: "ICICI Bank",
        type: "Private Commercial Bank",
        logoText: "ICICI",
        indicativeRate: "8.45% – 8.95%",
        maxDisbursalDays: 4,
        matchScore: 91,
        featureHighlight: "Pre-approved projects with zero valuation delays",
      },
    ],
  },
  {
    id: "mortgage-loan",
    name: "Mortgage Loan",
    shortName: "Mortgage Loan (LAP)",
    category: "Property & Housing",
    facilityType: "term_loan",
    badge: "High Loan-to-Value",
    rateText: "From 9.00% p.a.",
    annualRate: 9.0,
    minAmount: 1000000,
    maxAmount: 250000000,
    defaultAmount: 15000000,
    minTenureYears: 1,
    maxTenureYears: 15,
    defaultTenureYears: 10,
    description: "Unlock high-ticket liquidity against your self-occupied, rented residential, or freehold commercial property for business expansion.",
    highlights: [
      "Up to 70% Loan-to-Value (LTV) on property valuation",
      "Tenures up to 15 years for comfortable EMIs",
      "Accepts both residential and approved commercial assets",
      "Funds usable for any legitimate trade or personal need",
    ],
    eligibilityCriteria: [
      "Property owners with clear freehold or registered leasehold titles",
      "Business entities with minimum 3 years vintage",
      "Debt Service Coverage Ratio (DSCR) ≥ 1.25",
      "Clean credit bureau record without recent default write-offs",
    ],
    requiredDocuments: [
      "Complete chain of title deeds & approved sanction plan",
      "Audited balance sheet & P&L statements (3 years)",
      "Bank statements (all operative accounts, 12 months)",
      "Entity KYC (PAN, GSTIN, MOA/AOA, Partnership Deed)",
    ],
    matchedLenders: [
      {
        id: "axis",
        name: "Axis Bank",
        type: "Private Commercial Bank",
        logoText: "AXIS",
        indicativeRate: "9.00% – 9.85%",
        maxDisbursalDays: 7,
        matchScore: 93,
        featureHighlight: "Higher LTV up to 75% on prime city properties",
      },
      {
        id: "bajaj",
        name: "Bajaj Housing Finance",
        type: "NBFC",
        logoText: "BAJAJ",
        indicativeRate: "9.15% – 10.25%",
        maxDisbursalDays: 4,
        matchScore: 90,
        featureHighlight: "Flexible hybrid flexi-term loan structure",
      },
    ],
  },
  {
    id: "affordable-housing-loan",
    name: "Affordable Housing Loan",
    shortName: "Affordable Housing",
    category: "Property & Housing",
    facilityType: "term_loan",
    badge: "PMAY Subsidized",
    rateText: "From 7.90% p.a.",
    annualRate: 7.9,
    minAmount: 300000,
    maxAmount: 3500000,
    defaultAmount: 1800000,
    minTenureYears: 1,
    maxTenureYears: 25,
    defaultTenureYears: 20,
    description: "Government-subsidized home loan designed for Economically Weaker Sections (EWS) and Low-Income Groups (LIG) with lower processing costs.",
    highlights: [
      "Interest subsidy support under PMAY Urban/Gramin guidelines",
      "Relaxed banking surrogate income assessments",
      "Minimal stamp duty and subsidized processing fees",
      "Co-applicant support from female family members",
    ],
    eligibilityCriteria: [
      "Household annual income within prescribed EWS/LIG limits",
      "First-time home buyer without pucca residential dwelling",
      "Property carpet area compliant with affordable housing norms",
    ],
    requiredDocuments: [
      "Aadhaar, Voter ID, and Ration Card",
      "Salary slips / Cash income proof / Form 16",
      "Bank passbook statements (6 months)",
      "Builder allotment letter or property sale agreement",
    ],
    matchedLenders: [
      {
        id: "aavas",
        name: "Aavas Financiers",
        type: "NBFC",
        logoText: "AAVAS",
        indicativeRate: "7.90% – 8.85%",
        maxDisbursalDays: 5,
        matchScore: 97,
        featureHighlight: "Specialist underwriting for informal income sources",
      },
      {
        id: "hudco",
        name: "HUDCO / PNB Housing",
        type: "Development Financial Institution",
        logoText: "HUDCO",
        indicativeRate: "8.10% – 8.75%",
        maxDisbursalDays: 7,
        matchScore: 92,
        featureHighlight: "Official PMAY subsidy crediting window",
      },
    ],
  },
  {
    id: "commercial-property-loan",
    name: "Commercial Property Loan",
    shortName: "Commercial Property",
    category: "Property & Housing",
    facilityType: "term_loan",
    badge: "Office & Industrial Asset",
    rateText: "From 9.25% p.a.",
    annualRate: 9.25,
    minAmount: 1500000,
    maxAmount: 500000000,
    defaultAmount: 25000000,
    minTenureYears: 1,
    maxTenureYears: 15,
    defaultTenureYears: 10,
    description: "Acquire commercial office spaces, industrial factory sheds, retail showrooms, or logistics warehouses with institutional credit backing.",
    highlights: [
      "Financing up to 65% of certified commercial market value",
      "Custom moratorium periods during construction fit-out",
      "Combined construction and purchase facility lines",
      "Corporate tax interest deductions under Income Tax Act",
    ],
    eligibilityCriteria: [
      "Registered corporate entity, partnership, or established proprietor",
      "Minimum 3 years profitable commercial operations",
      "Commercial zoning clearance & municipal occupancy certificates",
    ],
    requiredDocuments: [
      "Registered title deed, sanctioned municipal plan, and NOC",
      "Audited financial statements (3 years) with GSTR-9 filings",
      "Entity constitution documents and authorized signatory board resolution",
      "Bank statements of primary current account (12 months)",
    ],
    matchedLenders: [
      {
        id: "kotak",
        name: "Kotak Mahindra Bank",
        type: "Private Commercial Bank",
        logoText: "KOTAK",
        indicativeRate: "9.25% – 9.95%",
        maxDisbursalDays: 6,
        matchScore: 95,
        featureHighlight: "High-ticket capacity up to ₹50 Crore for corporate campuses",
      },
      {
        id: "bob",
        name: "Bank of Baroda",
        type: "Public Sector Bank",
        logoText: "BOB",
        indicativeRate: "9.30% – 10.15%",
        maxDisbursalDays: 8,
        matchScore: 91,
        featureHighlight: "Lower processing charges for MSME manufacturing units",
      },
    ],
  },
  {
    id: "lease-rental-discounting",
    name: "Lease Rental Discounting",
    shortName: "Lease Rental (LRD)",
    category: "Property & Housing",
    facilityType: "discounting",
    badge: "Rental Escrow Backed",
    rateText: "From 8.75% p.a.",
    annualRate: 8.75,
    minAmount: 5000000,
    maxAmount: 1000000000,
    defaultAmount: 50000000,
    minTenureYears: 1,
    maxTenureYears: 15,
    defaultTenureYears: 9,
    description: "Monetize long-term lease contracts with MNC, corporate, or institutional tenants. Obtain upfront term loans repaid via rental escrow accounts.",
    highlights: [
      "Discounting up to 85% of net present value (NPV) of future rentals",
      "Tenure matched with registered lease agreement duration",
      "Tripartite agreement between borrower, lender, and tenant",
      "Repayments collected directly via automated Escrow / RTGS",
    ],
    eligibilityCriteria: [
      "Commercial real estate leased to reputed corporate/MNC tenants",
      "Minimum unexpired lease lock-in period of 3+ years",
      "Regular rental deposit track record over past 6-12 months",
    ],
    requiredDocuments: [
      "Registered Lease Deed with tenant stamp & lock-in terms",
      "Property title documents & municipal tax receipts",
      "Tenant corporate profile & rental payment bank credits (12 mo)",
      "Borrower entity balance sheets & KYC",
    ],
    matchedLenders: [
      {
        id: "icici-lrd",
        name: "ICICI Bank Commercial",
        type: "Private Commercial Bank",
        logoText: "ICICI",
        indicativeRate: "8.75% – 9.40%",
        maxDisbursalDays: 7,
        matchScore: 98,
        featureHighlight: "Institutional LRD desks for tech parks and retail malls",
      },
      {
        id: "tata-cap",
        name: "Tata Capital",
        type: "NBFC",
        logoText: "TATA",
        indicativeRate: "8.95% – 9.75%",
        maxDisbursalDays: 5,
        matchScore: 93,
        featureHighlight: "Quick escrow structuring for Grade-A/B commercial assets",
      },
    ],
  },
  {
    id: "business-loan",
    name: "Business Loan",
    shortName: "Business Loan",
    category: "Business & MSME",
    facilityType: "term_loan",
    badge: "100% Unsecured",
    rateText: "From 12.50% p.a.",
    annualRate: 12.5,
    minAmount: 100000,
    maxAmount: 7500000,
    defaultAmount: 2000000,
    minTenureYears: 1,
    maxTenureYears: 5,
    defaultTenureYears: 3,
    description: "Collateral-free commercial capital for immediate business expansion, bulk inventory procurement, staff payroll, or operational scaling.",
    highlights: [
      "Zero collateral or asset hypothecation required",
      "Disbursal within 24 to 48 hours upon document verification",
      "Customized repayment schedules based on monthly revenue",
      "Sanctions up to ₹75 Lakhs based on banking turnover",
    ],
    eligibilityCriteria: [
      "Business vintage of at least 2 years with continuous operations",
      "Minimum annual GST turnover of ₹40 Lakhs",
      "Healthy banking average monthly balance (AMB)",
      "Promoter CIBIL score ≥ 680",
    ],
    requiredDocuments: [
      "12 months official primary current account bank statements",
      "Last 2 years filed ITRs along with computation & audited balance sheets",
      "GST registration certificate and 12-month GSTR-3B filings",
      "Promoter KYC (PAN, Aadhaar, Business Address Proof)",
    ],
    matchedLenders: [
      {
        id: "hdfc-biz",
        name: "HDFC Bank Business Banking",
        type: "Private Commercial Bank",
        logoText: "HDFC",
        indicativeRate: "12.50% – 14.50%",
        maxDisbursalDays: 2,
        matchScore: 96,
        featureHighlight: "Instant digital sanction for GST-registered entities",
      },
      {
        id: "bajaj-biz",
        name: "Bajaj Finserv",
        type: "NBFC",
        logoText: "BAJAJ",
        indicativeRate: "13.00% – 16.00%",
        maxDisbursalDays: 1,
        matchScore: 94,
        featureHighlight: "Flexi-loan variant: withdraw & prepay anytime without charge",
      },
    ],
  },
  {
    id: "retail-shopkeeper-loan",
    name: "Retail Shopkeeper Loan",
    shortName: "Retail Shopkeeper",
    category: "Business & MSME",
    facilityType: "term_loan",
    badge: "Daily / Weekly EMI",
    rateText: "From 13.00% p.a.",
    annualRate: 13.0,
    minAmount: 50000,
    maxAmount: 2500000,
    defaultAmount: 500000,
    minTenureYears: 1,
    maxTenureYears: 3,
    defaultTenureYears: 2,
    description: "Designed for local retailers, distributors, and kirana shop owners. Backed by daily UPI QR code flows and POS card machine swipe volumes.",
    highlights: [
      "No complex audited financial statements required",
      "Repayments aligned with daily business collections (NACH / e-Mandate)",
      "Quick credit lines for festival seasonal stock build-up",
      "Approval based on UPI QR settlement velocity",
    ],
    eligibilityCriteria: [
      "Active retail shop, trading outlet, or local grocery store (1+ yr)",
      "Daily digital collections through QR codes, POS, or merchant accounts",
      "Shop ownership or registered shop-and-establishment license",
    ],
    requiredDocuments: [
      "Shop & Establishment license (Gumasta) or trade license",
      "6 months bank statement showing daily QR / settlement credits",
      "Promoter Aadhaar & PAN card",
      "Electricity bill of shop premises",
    ],
    matchedLenders: [
      {
        id: "bharatpe",
        name: "Unity Small Finance Bank",
        type: "Private Commercial Bank",
        logoText: "UNITY",
        indicativeRate: "13.00% – 15.50%",
        maxDisbursalDays: 1,
        matchScore: 95,
        featureHighlight: "Daily auto-deduction option matching merchant cash flows",
      },
      {
        id: "indifi",
        name: "Indifi Technologies",
        type: "NBFC",
        logoText: "INDIFI",
        indicativeRate: "13.50% – 16.50%",
        maxDisbursalDays: 2,
        matchScore: 91,
        featureHighlight: "Specialized merchant cash advance underwriting",
      },
    ],
  },
  {
    id: "sme-msme-loan",
    name: "SME-MSME Loan",
    shortName: "SME / MSME Loan",
    category: "Business & MSME",
    facilityType: "term_loan",
    badge: "CGTMSE Guarantee",
    rateText: "From 8.50% p.a.",
    annualRate: 8.5,
    minAmount: 500000,
    maxAmount: 50000000,
    defaultAmount: 7500000,
    minTenureYears: 1,
    maxTenureYears: 7,
    defaultTenureYears: 5,
    description: "Priority sector term loan for Micro, Small, and Medium Enterprises. Available under CGTMSE scheme with government credit guarantee.",
    highlights: [
      "Collateral-free lending up to ₹5 Crore under CGTMSE",
      "Subsidized interest rates under RBI priority sector guidelines",
      "Support for capital expenditure (CAPEX) and machinery modernization",
      "Tenure up to 7 years with initial principal moratorium",
    ],
    eligibilityCriteria: [
      "Valid Udyam Registration Certificate (Micro, Small, or Medium)",
      "Manufacturing or services enterprise with 2+ years track record",
      "No historical non-performing asset (NPA) classification",
    ],
    requiredDocuments: [
      "Udyam Registration Certificate & MSME classification proof",
      "3 years audited balance sheets with tax audit report & Form 3CD",
      "12 months bank statements & GSTR-1/3B summary",
      "Project report or quotation for machinery/expansion investment",
    ],
    matchedLenders: [
      {
        id: "sidbi",
        name: "SIDBI Direct",
        type: "Development Financial Institution",
        logoText: "SIDBI",
        indicativeRate: "8.50% – 9.25%",
        maxDisbursalDays: 6,
        matchScore: 99,
        featureHighlight: "Direct institutional refinance with lowest processing fees",
      },
      {
        id: "pnb",
        name: "Punjab National Bank MSME",
        type: "Public Sector Bank",
        logoText: "PNB",
        indicativeRate: "8.65% – 9.45%",
        maxDisbursalDays: 7,
        matchScore: 94,
        featureHighlight: "Full CGTMSE coverage with zero third-party guarantee",
      },
    ],
  },
  {
    id: "vendor-finance",
    name: "Vendor Finance",
    shortName: "Vendor Financing",
    category: "Business & MSME",
    facilityType: "discounting",
    badge: "Invoice Discounting",
    rateText: "From 0.90% / mo (10.8% p.a.)",
    annualRate: 10.8,
    minAmount: 100000,
    maxAmount: 100000000,
    defaultAmount: 5000000,
    minTenureYears: 1,
    maxTenureYears: 1,
    defaultTenureYears: 1,
    description: "Convert unpaid supplier invoices and trade receivables into immediate cash within 24 hours without waiting for 60 to 90-day buyer payment terms.",
    highlights: [
      "Early cash payment up to 90% of accepted invoice value",
      "Off-balance-sheet or clean working capital structure",
      "Integration with TReDS platforms (RXIL, M1xchange, Invoicemart)",
      "Anchor buyer credit rating unlocks cheaper cost of funds",
    ],
    eligibilityCriteria: [
      "Vendors supplying goods/services to established corporate buyers or PSUs",
      "Accepted and verified commercial invoices with proof of delivery (POD)",
      "Clean GST compliance track record on outward GSTR-1 supplies",
    ],
    requiredDocuments: [
      "Verified commercial tax invoices with Buyer Purchase Orders (POs)",
      "Goods receipt note (GRN) or signed Delivery Challan (POD)",
      "6 months bank statement showing buyer payment settlements",
      "Vendor GSTIN and corporate KYC",
    ],
    matchedLenders: [
      {
        id: "m1x",
        name: "M1xchange / TReDS Gateway",
        type: "Development Financial Institution",
        logoText: "TReDS",
        indicativeRate: "8.50% – 10.50% p.a.",
        maxDisbursalDays: 1,
        matchScore: 98,
        featureHighlight: "Competitive reverse-auction bidding by 40+ banks",
      },
      {
        id: "kredx",
        name: "KredX Enterprise Capital",
        type: "NBFC",
        logoText: "KREDX",
        indicativeRate: "10.00% – 12.00% p.a.",
        maxDisbursalDays: 1,
        matchScore: 92,
        featureHighlight: "Private corporate invoice discounting without TReDS mandate",
      },
    ],
  },
  {
    id: "overdraft-loan",
    name: "Overdraft Loan",
    shortName: "Overdraft (OD)",
    category: "Business & MSME",
    facilityType: "revolving_credit",
    badge: "Pay For Used Days",
    rateText: "From 9.50% p.a.",
    annualRate: 9.5,
    minAmount: 500000,
    maxAmount: 150000000,
    defaultAmount: 10000000,
    minTenureYears: 1,
    maxTenureYears: 5,
    defaultTenureYears: 1,
    description: "Revolving credit limit linked to your commercial current account. Draw funds anytime and pay interest strictly on the utilized amount and exact days used.",
    highlights: [
      "Interest calculated on daily closing debit balance",
      "Deposit surplus cash anytime to instantly reduce interest liability",
      "Annual renewable credit line with simple review procedures",
      "Available against property collateral, fixed deposits, or clean turnover",
    ],
    eligibilityCriteria: [
      "Active current account with consistent debit and credit rotation",
      "Business operation vintage of minimum 2 years",
      "Eligible property or financial asset for secured OD lines",
    ],
    requiredDocuments: [
      "12 months current account bank statements",
      "Property title papers (if applying for Drop-Line / Property OD)",
      "2 years audited balance sheets & tax computation",
      "Business registration & GST certificates",
    ],
    matchedLenders: [
      {
        id: "sbi-od",
        name: "SBI SME Current OD",
        type: "Public Sector Bank",
        logoText: "SBI",
        indicativeRate: "9.50% – 10.25%",
        maxDisbursalDays: 5,
        matchScore: 96,
        featureHighlight: "Lowest commitment fees on unutilized overdraft limits",
      },
      {
        id: "hdfc-od",
        name: "HDFC Smart Overdraft",
        type: "Private Commercial Bank",
        logoText: "HDFC",
        indicativeRate: "9.75% – 11.00%",
        maxDisbursalDays: 3,
        matchScore: 94,
        featureHighlight: "Instant digital drawdown via NetBanking and corporate mobile app",
      },
    ],
  },
  {
    id: "cash-credit-loan",
    name: "Cash Credit Loan",
    shortName: "Cash Credit (CC)",
    category: "Business & MSME",
    facilityType: "revolving_credit",
    badge: "Stock & Debtors Backed",
    rateText: "From 9.25% p.a.",
    annualRate: 9.25,
    minAmount: 1000000,
    maxAmount: 250000000,
    defaultAmount: 20000000,
    minTenureYears: 1,
    maxTenureYears: 5,
    defaultTenureYears: 1,
    description: "Continuous working capital facility backed by the hypothecation of raw materials, work-in-progress, finished inventory, and trade debtors.",
    highlights: [
      "Drawing Power (DP) calculated on monthly submitted stock statements",
      "Ideal for manufacturing, industrial distribution, and trading entities",
      "Lower interest cost than unsecured business credit",
      "Enhancement possible as company sales volumes scale up",
    ],
    eligibilityCriteria: [
      "Manufacturers and traders with structured stock auditing",
      "Working capital operating cycle between 60 and 120 days",
      "Minimum annual audited sales turnover of ₹1.5 Crore",
    ],
    requiredDocuments: [
      "Certified monthly Stock & Book Debts statement with age-wise debtors",
      "Last 3 years audited balance sheets and CMA data projections",
      "Primary bank statements (12 months)",
      "Stock insurance policy with bank hypothecation clause",
    ],
    matchedLenders: [
      {
        id: "canara-cc",
        name: "Canara Bank Industrial Finance",
        type: "Public Sector Bank",
        logoText: "CANARA",
        indicativeRate: "9.25% – 10.00%",
        maxDisbursalDays: 7,
        matchScore: 95,
        featureHighlight: "Supportive margin requirements for MSME manufacturers",
      },
      {
        id: "idfc-cc",
        name: "IDFC FIRST Bank",
        type: "Private Commercial Bank",
        logoText: "IDFC",
        indicativeRate: "9.50% – 10.75%",
        maxDisbursalDays: 4,
        matchScore: 92,
        featureHighlight: "Paperless monthly stock statement upload via corporate portal",
      },
    ],
  },
  {
    id: "export-credit",
    name: "Export Credit",
    shortName: "Export Credit",
    category: "Trade & Working Capital",
    facilityType: "revolving_credit",
    badge: "Subsidized FX Line",
    rateText: "From 4.50% p.a. (Subsidized)",
    annualRate: 4.5,
    minAmount: 1000000,
    maxAmount: 500000000,
    defaultAmount: 30000000,
    minTenureYears: 1,
    maxTenureYears: 1,
    defaultTenureYears: 1,
    description: "Comprehensive foreign trade finance covering Pre-shipment Packing Credit (PCFC) and Post-shipment Export Bill Discounting in INR or Foreign Currency.",
    highlights: [
      "Interest Equalisation Scheme (IES) interest subsidy benefits",
      "Borrow in USD, EUR, or GBP at SOFR-linked international rates",
      "Direct settlement against overseas export realisations",
      "ECGC credit insurance coverage integration",
    ],
    eligibilityCriteria: [
      "Valid Import Export Code (IEC) issued by DGFT",
      "Confirmed export order or irrevocable Letter of Credit (LC)",
      "Clear screening against DGFT Denied Entity List (DPL)",
    ],
    requiredDocuments: [
      "DGFT IEC certificate and RCMC registration",
      "Confirmed Export Purchase Order / Letter of Credit",
      "Shipping bills and bill of lading for post-shipment bills",
      "3 years audited financial statements with export turnover ledger",
    ],
    matchedLenders: [
      {
        id: "exim",
        name: "Export-Import Bank of India",
        type: "Development Financial Institution",
        logoText: "EXIM",
        indicativeRate: "4.50% – 6.50%",
        maxDisbursalDays: 5,
        matchScore: 98,
        featureHighlight: "Direct access to international trade lines and buyer credit",
      },
      {
        id: "sbi-export",
        name: "State Bank of India International",
        type: "Public Sector Bank",
        logoText: "SBI",
        indicativeRate: "5.00% – 7.25%",
        maxDisbursalDays: 4,
        matchScore: 96,
        featureHighlight: "Full PCFC disbursement in USD/EUR within 48 hours",
      },
    ],
  },
  {
    id: "bank-guarantee",
    name: "Bank Guarantee",
    shortName: "Bank Guarantee (BG)",
    category: "Trade & Working Capital",
    facilityType: "guarantee",
    badge: "Government Tender Backed",
    rateText: "0.75% – 2.50% Commission p.a.",
    annualRate: 1.5,
    minAmount: 200000,
    maxAmount: 250000000,
    defaultAmount: 10000000,
    minTenureYears: 1,
    maxTenureYears: 3,
    defaultTenureYears: 1,
    description: "Institutional Financial and Performance Bank Guarantees required for government bids, EPC contracts, earnest money deposits (EMD), and procurement security.",
    highlights: [
      "Issued under SFMS (Structured Financial Messaging System) to beneficiary bank",
      "Covers Tender EMD, Performance Guarantees, and Advance Payment BGs",
      "Low cash margin requirements (10% - 25% depending on balance sheet)",
      "Zero fund outflow except issuance commission",
    ],
    eligibilityCriteria: [
      "Government contractors, infrastructure builders, and enterprise suppliers",
      "Proven contract execution capability and technical track record",
      "Adequate collateral or liquid fixed deposit margin",
    ],
    requiredDocuments: [
      "Tender document / Letter of Award (LOA) / Contract agreement",
      "Draft BG text approved by the beneficiary authority",
      "Audited financial accounts (3 years) with Net Worth certificate",
      "Board resolution authorizing BG execution",
    ],
    matchedLenders: [
      {
        id: "pnb-bg",
        name: "PNB Commercial Services",
        type: "Public Sector Bank",
        logoText: "PNB",
        indicativeRate: "0.75% – 1.50% commission",
        maxDisbursalDays: 2,
        matchScore: 97,
        featureHighlight: "Instant SFMS transmission to all central/state government departments",
      },
      {
        id: "icici-bg",
        name: "ICICI Corporate Banking",
        type: "Private Commercial Bank",
        logoText: "ICICI",
        indicativeRate: "1.00% – 1.85% commission",
        maxDisbursalDays: 1,
        matchScore: 95,
        featureHighlight: "Digital e-BG issuance via NeSL with instant beneficiary verification",
      },
    ],
  },
  {
    id: "study-abroad-loan",
    name: "Study Abroad Loan",
    shortName: "Study Abroad Loan",
    category: "Professional & Education",
    facilityType: "term_loan",
    badge: "100% Cost Coverage",
    rateText: "From 8.85% p.a.",
    annualRate: 8.85,
    minAmount: 500000,
    maxAmount: 15000000,
    defaultAmount: 4000000,
    minTenureYears: 1,
    maxTenureYears: 15,
    defaultTenureYears: 10,
    description: "Financing for students pursuing higher education abroad in USA, UK, Canada, Germany, and Australia. Covers tuition, living, books, and visa proof.",
    highlights: [
      "Unsecured loans up to ₹75 Lakhs for top-ranked global universities",
      "Pre-visa sanction letter for swift embassy visa approval",
      "Moratorium period: Course duration + 6 to 12 months grace period",
      "Tax deduction on interest paid under Section 80E with no upper limit",
    ],
    eligibilityCriteria: [
      "Indian national with confirmed admission to recognized overseas university",
      "Co-applicant (parent/guardian) with steady income and healthy CIBIL",
      "Good academic track record in undergraduate/school degrees",
    ],
    requiredDocuments: [
      "University Admission Offer Letter & I-20 / CAS document",
      "Academic marksheets (10th, 12th, Degree) and GRE/GMAT/IELTS scorecards",
      "Co-borrower KYC, salary slips / ITRs, and 6 months bank statements",
      "Cost of education breakdown from university",
    ],
    matchedLenders: [
      {
        id: "avanse",
        name: "Avanse Financial Services",
        type: "NBFC",
        logoText: "AVANSE",
        indicativeRate: "9.25% – 11.50%",
        maxDisbursalDays: 3,
        matchScore: 97,
        featureHighlight: "100% financing including overseas living expenses and insurance",
      },
      {
        id: "sbi-edu",
        name: "SBI Global Ed-Vantage",
        type: "Public Sector Bank",
        logoText: "SBI",
        indicativeRate: "8.85% – 9.65%",
        maxDisbursalDays: 6,
        matchScore: 94,
        featureHighlight: "Concessional rates for secured education loans against property",
      },
    ],
  },
  {
    id: "doctor-loan",
    name: "Doctor Loan",
    shortName: "Doctor Loan",
    category: "Professional & Education",
    facilityType: "term_loan",
    badge: "Zero Collateral up to ₹50L",
    rateText: "From 9.75% p.a.",
    annualRate: 9.75,
    minAmount: 200000,
    maxAmount: 10000000,
    defaultAmount: 3500000,
    minTenureYears: 1,
    maxTenureYears: 7,
    defaultTenureYears: 5,
    description: "Specialized credit line tailored for qualified MBBS, MD, MS, BDS, and MDS doctors for setting up clinics, consulting chambers, or personal requirements.",
    highlights: [
      "Zero collateral required up to ₹50 Lakhs limit",
      "Simplified document processing based on medical qualification certificate",
      "Special discounted interest rates for medical specialists",
      "Minimal verification formalities with express 24-hour disbursal",
    ],
    eligibilityCriteria: [
      "Qualified Doctor (MBBS, MD, MS, BDS, MDS, BHMS/BAMS with min experience)",
      "Registration with Medical Council of India (MCI) or State Medical Council",
      "Minimum 2 years of post-qualification professional practice",
    ],
    requiredDocuments: [
      "Medical degree certificate and State / MCI registration certificate",
      "Last 6 months operative bank account statements",
      "PAN Card, Aadhaar Card, and Clinic Address Proof",
      "Last 2 years ITR (if available)",
    ],
    matchedLenders: [
      {
        id: "hdfc-doc",
        name: "HDFC Professional Loans",
        type: "Private Commercial Bank",
        logoText: "HDFC",
        indicativeRate: "9.75% – 11.25%",
        maxDisbursalDays: 1,
        matchScore: 98,
        featureHighlight: "Pre-approved limits based on medical specialization tier",
      },
      {
        id: "bajaj-doc",
        name: "Bajaj Finserv Doctor Finance",
        type: "NBFC",
        logoText: "BAJAJ",
        indicativeRate: "10.00% – 12.00%",
        maxDisbursalDays: 1,
        matchScore: 95,
        featureHighlight: "Doorstep service & minimal documentation for busy doctors",
      },
    ],
  },
  {
    id: "used-car-finance",
    name: "Used Car Finance",
    shortName: "Used Car Finance",
    category: "Vehicles & Equipment",
    facilityType: "term_loan",
    badge: "Up to 90% Valuation",
    rateText: "From 11.00% p.a.",
    annualRate: 11.0,
    minAmount: 100000,
    maxAmount: 5000000,
    defaultAmount: 800000,
    minTenureYears: 1,
    maxTenureYears: 7,
    defaultTenureYears: 4,
    description: "Fast financing for certified pre-owned passenger cars, SUVs, and luxury pre-owned vehicles with doorstep valuation and RTO transfer support.",
    highlights: [
      "Funding up to 90% of vehicle valuation or purchase value",
      "Tenure up to 7 years for low monthly EMIs",
      "Comprehensive RTO title transfer and hypothecation management",
      "Applicable for certified dealer or direct individual seller purchases",
    ],
    eligibilityCriteria: [
      "Salaried individuals or business owners with steady monthly cash flow",
      "Vehicle age not exceeding 10 years at loan maturity",
      "Clean RTO record without total loss or legal dispute flags",
    ],
    requiredDocuments: [
      "Vehicle Registration Certificate (RC Copy) and Insurance Policy",
      "Salary slips (3 months) or Business ITR (2 years)",
      "Bank statements (6 months)",
      "KYC (PAN & Aadhaar)",
    ],
    matchedLenders: [
      {
        id: "hdfc-auto",
        name: "HDFC Bank Used Car Loans",
        type: "Private Commercial Bank",
        logoText: "HDFC",
        indicativeRate: "11.00% – 13.50%",
        maxDisbursalDays: 2,
        matchScore: 96,
        featureHighlight: "Integrated digital valuation and instant transfer sanction",
      },
      {
        id: "mahindra-fin",
        name: "Mahindra Finance",
        type: "NBFC",
        logoText: "MMFSL",
        indicativeRate: "11.50% – 14.50%",
        maxDisbursalDays: 2,
        matchScore: 92,
        featureHighlight: "Deep Tier-2/3 dealer network and flexible surrogate policies",
      },
    ],
  },
  {
    id: "balance-transfer-loan",
    name: "Balance Transfer Loan",
    shortName: "Balance Transfer",
    category: "Professional & Education",
    facilityType: "term_loan",
    badge: "Cut EMI + Top-Up Cash",
    rateText: "From 8.25% p.a.",
    annualRate: 8.25,
    minAmount: 500000,
    maxAmount: 250000000,
    defaultAmount: 6000000,
    minTenureYears: 1,
    maxTenureYears: 30,
    defaultTenureYears: 15,
    description: "Transfer existing high-interest home, mortgage (LAP), or business loans to top banks at lower interest rates. Access extra top-up capital at identical low rates.",
    highlights: [
      "Save ₹5 Lakhs to ₹30 Lakhs in total interest over loan life",
      "Substantial Top-Up capital line disbursed with zero extra collateral",
      "Direct balance takeover from current bank/NBFC with NOC support",
      "Option to reduce EMI amount or shorten overall loan tenure",
    ],
    eligibilityCriteria: [
      "Existing loan running for at least 12 months with clean repayment track",
      "Zero defaults or delayed EMI bounces in past 12 months",
      "Adequate property valuation headroom for requested top-up amount",
    ],
    requiredDocuments: [
      "Existing loan sanction letter, repayment schedule & 12-month loan track",
      "Foreclosure letter & List of Documents (LOD) from current lender",
      "Last 6 months primary bank statements showing regular EMI debits",
      "Borrower income documents (ITR / Salary slips)",
    ],
    matchedLenders: [
      {
        id: "sbi-bt",
        name: "SBI Balance Transfer Desk",
        type: "Public Sector Bank",
        logoText: "SBI",
        indicativeRate: "8.25% – 8.55%",
        maxDisbursalDays: 7,
        matchScore: 99,
        featureHighlight: "Zero processing charges during festive takeover campaigns",
      },
      {
        id: "kotak-bt",
        name: "Kotak Mahindra Takeover",
        type: "Private Commercial Bank",
        logoText: "KOTAK",
        indicativeRate: "8.35% – 8.75%",
        maxDisbursalDays: 4,
        matchScore: 95,
        featureHighlight: "Highest Top-Up multiplier up to 100% of original loan amount",
      },
    ],
  },
  {
    id: "medical-equipment-loan",
    name: "Medical Equipment Loan",
    shortName: "Medical Equipment",
    category: "Vehicles & Equipment",
    facilityType: "term_loan",
    badge: "Equipment Hypothecation",
    rateText: "From 8.90% p.a.",
    annualRate: 8.9,
    minAmount: 500000,
    maxAmount: 200000000,
    defaultAmount: 15000000,
    minTenureYears: 1,
    maxTenureYears: 7,
    defaultTenureYears: 5,
    description: "Financing for hospitals, diagnostic centers, pathology labs, and specialty doctors to procure MRI, CT scan, digital X-Ray, ultrasound, and ICU equipment.",
    highlights: [
      "Financing up to 85% - 90% of equipment invoice value (ex-factory / imported)",
      "Loan secured exclusively by hypothecation of procured medical machinery",
      "Structured repayments with initial moratorium till commercial commissioning",
      "Substantial tax depreciation write-offs under Section 32 of Income Tax Act",
    ],
    eligibilityCriteria: [
      "Hospitals, nursing homes, imaging clinics, or medical diagnostic chains",
      "Minimum 3 years operational standing with positive EBITDA",
      "Equipment from approved international/national medical OEMs (Siemens, GE, Philips)",
    ],
    requiredDocuments: [
      "Proforma invoice / purchase quotation from certified medical equipment vendor",
      "Hospital registration certificate and statutory pollution/clinical NOCs",
      "3 years audited financial statements with doctor partner credentials",
      "12 months bank statements of hospital operational accounts",
    ],
    matchedLenders: [
      {
        id: "siemens-fin",
        name: "Siemens Financial Services",
        type: "NBFC",
        logoText: "SIEMENS",
        indicativeRate: "8.90% – 9.60%",
        maxDisbursalDays: 4,
        matchScore: 98,
        featureHighlight: "Direct OEM manufacturer financing with subsidized maintenance tie-ins",
      },
      {
        id: "icici-med",
        name: "ICICI Healthcare Finance",
        type: "Private Commercial Bank",
        logoText: "ICICI",
        indicativeRate: "9.10% – 9.95%",
        maxDisbursalDays: 5,
        matchScore: 94,
        featureHighlight: "High-ticket lines up to ₹20 Crore for super-specialty hospitals",
      },
    ],
  },
  {
    id: "commercial-vehicle-loan",
    name: "Commercial Vehicle Loan",
    shortName: "Commercial Vehicle",
    category: "Vehicles & Equipment",
    facilityType: "term_loan",
    badge: "Fleet & Heavy Trucks",
    rateText: "From 9.50% p.a.",
    annualRate: 9.5,
    minAmount: 300000,
    maxAmount: 15000000,
    defaultAmount: 2500000,
    minTenureYears: 1,
    maxTenureYears: 5,
    defaultTenureYears: 4,
    description: "Vehicle loans for fleet operators, logistics companies, and transport contractors. Covers heavy trucks, prime movers, tippers, tankers, and buses.",
    highlights: [
      "Funding up to 90% of chassis and complete body-building costs",
      "Fleet financing programs for operators holding 5 to 500+ commercial vehicles",
      "National Permit and FASTag GPS telematics integration",
      "Working capital fuel card and tyre loan add-on lines",
    ],
    eligibilityCriteria: [
      "Fleet operators or transport entrepreneurs with experience in logistics",
      "Valid commercial driving licenses or fleet management contracts",
      "Clean track record on existing commercial vehicle EMI repayments",
    ],
    requiredDocuments: [
      "Chassis proforma quotation from authorized commercial dealer (Tata, Ashok Leyland)",
      "Existing fleet RC copies and national road permit papers",
      "6 to 12 months bank statements showing freight collection turnover",
      "Transport contract agreements with cement, steel, or FMCG shippers",
    ],
    matchedLenders: [
      {
        id: "tata-motors-fin",
        name: "Tata Motors Finance",
        type: "NBFC",
        logoText: "TMFL",
        indicativeRate: "9.50% – 11.50%",
        maxDisbursalDays: 2,
        matchScore: 97,
        featureHighlight: "Fastest showroom delivery with factory warranty tie-ins",
      },
      {
        id: "shriram-fin",
        name: "Shriram Finance",
        type: "NBFC",
        logoText: "SHRIRAM",
        indicativeRate: "10.00% – 12.50%",
        maxDisbursalDays: 2,
        matchScore: 93,
        featureHighlight: "Industry leader for first-time buyers and small fleet owners",
      },
    ],
  },
  {
    id: "construction-equipment-loan",
    name: "Construction Equipment Loan",
    shortName: "Construction Equipment",
    category: "Vehicles & Equipment",
    facilityType: "term_loan",
    badge: "Heavy Machinery Line",
    rateText: "From 9.25% p.a.",
    annualRate: 9.25,
    minAmount: 500000,
    maxAmount: 50000000,
    defaultAmount: 7000000,
    minTenureYears: 1,
    maxTenureYears: 5,
    defaultTenureYears: 4,
    description: "Asset finance for infrastructure contractors and EPC builders to acquire hydraulic excavators, backhoe loaders, mobile cranes, and transit mixers.",
    highlights: [
      "Financing up to 85% - 90% of machine invoice value",
      "Structured repayments aligned with government and road EPC work contracts",
      "Covers world-class equipment OEMs: JCB, Caterpillar, Komatsu, L&T, Sany",
      "Option for refinancing unencumbered existing construction fleets",
    ],
    eligibilityCriteria: [
      "Civil contractors, mining operators, and road construction companies",
      "Minimum 2 years of active work-order contract execution experience",
      "Sufficient machine utilization hours to service debt",
    ],
    requiredDocuments: [
      "Machine quotation from authorized OEM equipment dealer",
      "Copies of ongoing / awarded infrastructure work orders & contracts",
      "2 years audited balance sheets and 12 months banking statements",
      "Company registration, GSTIN, and director KYC",
    ],
    matchedLenders: [
      {
        id: "srei",
        name: "L&T Finance Heavy Equipment",
        type: "NBFC",
        logoText: "L&T",
        indicativeRate: "9.25% – 10.50%",
        maxDisbursalDays: 3,
        matchScore: 98,
        featureHighlight: "In-depth technical knowledge of infrastructure machinery cycles",
      },
      {
        id: "hdb-ce",
        name: "HDB Financial Services",
        type: "NBFC",
        logoText: "HDB",
        indicativeRate: "9.50% – 11.00%",
        maxDisbursalDays: 4,
        matchScore: 92,
        featureHighlight: "Competitive rates for JCB and hydraulic excavator financing",
      },
    ],
  },
];
